API_KEY = "i7FDT8uRU3cK2ib6mt0Nz4mQZesgRSBlg9LIwectiocer9dzWfa6yUiwMzvkhslp"
API_SECRET = "QERzLALrtyF1kfz1TtQl3FcYHDALkdYPYqIZbaX96sBjFq0QP646fH7xEtUFPQlG"

TESTNET = True

# Strategy settings
RSI_PERIOD = 14
RSI_OVERSOLD = 35
RSI_OVERBOUGHT = 65

EMA_FAST = 9
EMA_SLOW = 21

VOLUME_MULTIPLIER = 1.2

# Risk
RISK_PER_TRADE = 0.02
MAX_TRADES_OPEN = 5
LEVERAGE = 5

# Bot settings
TIMEFRAME = "15m"
TOP_PAIRS = 20
SCAN_INTERVAL = 30

# Optional Telegram
TELEGRAM_TOKEN = ""
TELEGRAM_CHAT_ID = ""
